# Generated by Django 5.1.3 on 2024-11-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_tblcake'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblcake',
            old_name='cakeamount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='tblcake',
            old_name='cakeprice',
            new_name='cakeweight',
        ),
    ]
