# Generated by Django 5.1.3 on 2024-11-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_cakeamount_tblcake_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcake',
            name='amount',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tblcake',
            name='cakeweight',
            field=models.IntegerField(max_length=50),
        ),
    ]
