# Generated by Django 5.1.3 on 2024-11-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbluser',
            old_name='contactname',
            new_name='contactnumber',
        ),
    ]
