# Generated by Django 5.1.3 on 2024-11-16 12:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_tblcake_amount_alter_tblcake_cakeweight'),
        ('guestapp', '0001_initial'),
        ('userapp', '0002_rename_contactname_tbluser_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblbooking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryaddress', models.CharField(max_length=500)),
                ('requireddate', models.DateField()),
                ('quantity', models.IntegerField(max_length=50)),
                ('totalamount', models.IntegerField(max_length=50)),
                ('bookingdate', models.DateField(default=datetime.date(2024, 11, 16))),
                ('bookingstatus', models.CharField(max_length=50)),
                ('cakeid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adminapp.tblcake')),
                ('loginid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='guestapp.tbllogin')),
            ],
        ),
    ]
